In [1]:
import numpy as np

## turn
#### left: 0 -> 1 -> 2 -> 3 -> 0
#### right: 0 -> 3 -> 2 -> 1 -> 0

In [2]:
directions = np.array([[1, 0], [0, 1], [-1, 0], [0, -1]])
right = np.array([[0, 1], [-1, 0]])
left = np.array([[0, -1], [1, 0]])

In [3]:
i = 3
print(np.matmul(right, directions[i]))
print(directions[(i+3)%4])

[-1  0]
[-1  0]


In [4]:
i = 3
print(np.matmul(left, directions[i]))
print(directions[(i-3)%4])

[1 0]
[1 0]


In [5]:
a = np.array([[2, 0]])
b = np.array([[4, 0]])
np.matmul( (b - a), directions[0] )

array([2])

In [6]:
storage = dict()
storage['win'] = np.repeat(-1, 20)
storage['win'][0:3] = 1
storage['win'][4:9] = -99

In [7]:
np.array(np.where(storage['win'] == -99)).shape[1]

5

In [23]:
myField = np.random.randint(low=0, high=5, size=[20, 20])
enemy_bands = np.r_[np.c_[np.where(myField == 4)], np.c_[np.where(myField == 41)]]

In [24]:
my_pos = np.random.randint(low=0, high=5, size=[1, 2])

In [27]:
np.mean(np.abs(enemy_bands - my_pos))

7.3441558441558445

In [32]:
my_bands = np.c_[np.where(myField == 20)]
my_bands = np.r_[my_bands, my_pos]

In [33]:
my_bands

array([[2, 2]])

In [31]:
my_pos

array([[2, 2]])